### ISSUE TITLE
Support serialise nested object as nil 

### ISSUE THREAD

**Issue by ignacio-chiazzo** [Shopify/graphql_swift_gen#7]
We have to support sending a nested object as `nil` so as to delete the object. 

```
  objectUpdate(input: $input) {
        userErrors { field, message }
        object {
          id
          title
          suboject {
            id
            name
          }
        }
      }
    }
```

To do that we have to modify the `serialise` function.

**Comment by see-mack** [comment]
This is also affecting the android client. Is there an open issue to fix that as well?

**Comment by ignacio-chiazzo** [comment]
I created the ticket but haven't had a chance to look into it. It's not on my TODO plan now. But I can take a peek next week.

**Comment by ignacio-chiazzo** [comment]
Closing in favour of https://github.com/Shopify/graphql_swift_gen/pull/8
