### ISSUE TITLE
Gen fails to support Union spec

### ISSUE THREAD

**Issue by BenEmdon** [Shopify/graphql_swift_gen#9]
The [spec says](https://facebook.github.io/graphql/#sec-Union) that `union` types don't have any `field`s and only have possible object types.

It looks like the `union` implementation will require more thought. If you have any ideas talk here 👇 

Until then I will work up a fix so that gen doesn't crash in the meantime.

**Comment by dylanahsmith** [comment]
Looks like union support was fixed for java in https://github.com/shopify/graphql_java_gen/pull/21 but the fix wasn't ported to swift.
